apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backoffice
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./component/k8s-staging/namespace/backoffice
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system