apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: product-svc
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./component/k8s-staging/namespace/product-svc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system