apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payment-svc

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

configMapGenerator:
  - name: payment-config
    literals:
      - APP_VERSION=1.0
      - APP_DESCRIPTION=Ini aplikasi payment
generatorOptions:
  disableNameSuffixHash: true