---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product-svc
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm/application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  releaseName: product-svc
  values:
    image: nginx:stable-alpine-slim